<!DOCTYPE html>
<html>
<head>

<title>The Groovy 2 Tutorial - Try-Catch-Finally</title> 
<meta name="The Groovy 2 Tutorial" content="text/html; charset=utf-8" />
<meta name="description" content="The try-catch-finally statement is used for catching and handling exceptions and errors." />

<meta name="author" content="Duncan Dickinson" />

<link rel="icon" href="../../resources/images/gico.png">
<link rel="license" href="../../Licence.html">

<script type="text/javascript" src="../../resources/js/analytics.js">
<link href='http://fonts.googleapis.com/css?family=Oxygen+Mono|Oxygen' rel='stylesheet' type='text/css'>
<script type="text/javascript" src="http://cdn.mathjax.org/mathjax/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML">

</script>
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/highlight.js/8.4/styles/github.min.css">
<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/highlight.js/8.4/highlight.min.js"></script>
<script>
	hljs.initHighlightingOnLoad();
</script>
<link rel='stylesheet' type='text/css' href='../../resources/styles/site.css'>
</head>
<body>
  <header>
    <h1>The Groovy 2 Tutorial</h1>
  </header>
  <div class="content leftmenu">
    <div class="colright">
      <div class="col-article-wrap">
        <div class="col-article">
<article>
  <header>
    <h1 itemprop="headline">Try-Catch-Finally</h1>
    <nav class='part-nav'>
        <a href='../../parts/05_Exceptions/Anatomy.html' rel=prev>&laquo; Previous</a>&nbsp;&bull;&nbsp;<a href='../../parts/05_Exceptions/HowMuch.html' rel=next>Next &raquo;</a>
    </nav>
  </header>
  <div class='article-content'>
  <aside>The try-catch-finally statement is used for catching and handling exceptions and errors.</aside>
  <p>The <code>try-catch-finally</code> statement can have three forms:</p>

<ol>
<li><code>try-catch</code></li>
<li><code>try-catch-finally</code></li>
<li><code>try-finally</code></li>
</ol>

<p>Groovy doesn&#8217;t support the <code>try-with-resources</code> syntax available in Java. Groovy&#8217;s closure infrastructure often takes care of closing resources for you (you may not even need a <code>finally</code> block).<a href="#fn:1" id="fnref:1" title="see footnote" class="footnote">[1]</a> </p>

<h1>Scope</h1>

<p>Before getting into the specific syntax it&#8217;s important to point out that the <code>try</code> statement presents a block with its own scope. This means that variables declared within the <code>try</code> block can&#8217;t been seen outside the block. In the example below the <code>assert</code> fails not because <code>score</code> doesn&#8217;t equal 12 but because the <code>score</code> variable is out-of-scope:</p>

<pre><code class="groovy">try {
    def score = 12
} catch (any) {

}

assert score == 12
</code></pre>

<p>In fact, the <code>score</code> variable won&#8217;t be visible to the <code>catch</code> block or a <code>finally block</code>. If you do need to access <code>score</code> outside of the <code>try</code> block then you should declare it before the <code>try</code>:</p>

<pre><code class="groovy">def score
try {
    score = 12
} catch (any) {

}

assert score == 12
</code></pre>

<h1>try-catch</h1>

<p>The basic format of <code>try-catch</code> is as follows:</p>

<pre><code class="groovy">try {
    //statements...
} catch (&lt;Exception type&gt; &lt;var&gt;) {
    //statements...
}
</code></pre>

<p>If an exception occurs within the <code>try</code> block:</p>

<ul>
<li>The catch variable (<code>var</code>) is set to the exception instance</li>
<li>If <code>Exception type</code> is provided (this is optional) then the <code>catch</code> block will only be activated if the exception is of that type.</li>
</ul>

<p>In the following example I generate an exception on purpose by dividing 10 by 0. The <code>catch</code> block is set up to catch any exception raised:</p>

<pre><code class="groovy">try {
    10 / 0
} catch (any) {
    println any.message
    any.printStackTrace()
}
</code></pre>

<p>As we saw in an earlier chapter, exceptions in Groovy are objects - they have fields and methods, allowing me to display the <code>message</code> within the exception as well as display the stack trace.</p>

<blockquote>
<p>I like using <code>any</code> as the catch variable when I&#8217;m prepared to catch anything - it just reads nicely. However, you&#8217;re also likely to see <code>e</code>, <code>exc</code> or a shortened version of the exception name (e.g. <code>npe</code> for a <code>NullPointerException</code>).</p>
</blockquote>

<p>An Exception type can be provided for a <code>catch</code> block. In the example below I only catch an <code>ArithmeticException</code> - any other type of exception is raised up to the caller:</p>

<pre><code class="groovy">try {
    10 / 0
} catch (ArithmeticException e) {
    println 'I just caught an ArithmeticException'
}
</code></pre>

<p>A <code>try-catch</code> statement can consist of multiple <code>catch</code> blocks, each targeting specific exceptions. In this next example I explicitly catch <code>ArithmeticException</code> and have a default <code>catch</code> to pick up any other exception raised:</p>

<pre><code class="groovy">try {
    10 / 0
} catch (ArithmeticException e) {
    println 'I just caught an ArithmeticException'
} catch (any) {
    println 'What just happened?'
}
</code></pre>

<p>In this next example I explicitly catch <code>IllegalStateException</code> and <code>ArithmeticException</code> and have a default <code>catch</code> to pick up any other exception raised:</p>

<pre><code class="groovy">try {
    10 / 0
} catch (IllegalStateException e) {
    println 'I just caught an IllegalStateException'
} catch (ArithmeticException e) {
    println 'I just caught an ArithmeticException'
} catch (any) {
    println 'What just happened?'
}
</code></pre>

<blockquote>
<p>In that last example, <code>IllegalStateException</code> will never be raised but I&#8217;ve used it here to indicate syntax. Later in this chapter we&#8217;ll make this example more meaningful</p>
</blockquote>

<p>If we wanted to handle a number of exception types (sometimes called a multicatch) in the same manner, the <code>|</code> operator can be used within the same <code>catch</code> to provide a separator for the exception types:</p>

<pre><code class="groovy">try {
    10 / 0
} catch (IllegalStateException | ArithmeticException e) {
    println 'I just caught an exception I want to handle'
} catch (any) {
    println 'What just happened?'
}
</code></pre>

<p>The last <code>catch</code> block (<code>catch (any)</code>) is a very useful one to reflect on when considering how you deal with exceptions. By providing a <code>catch</code> block you are flagging an intent to actually do <strong>something useful</strong> with an exception. If you don&#8217;t actually intend to add any value to the situation then I&#8217;d suggest not catching the exception. That way it will pass up the chain to the calling code (which may chose to actually handle the exception). The buck stops at the top-level code (e.g. the script) and, without explicit handling, the exception will be displayed and the program halted.</p>

<p>My preference is to use <code>try-finally</code> if I just want to tidy up resources (such as files) if an exception occurs - that way the exception will pass up to the caller but I don&#8217;t get in the way. In most cases I use the explicit form of <code>catch</code> and indicate which Exception type I am prepared to handle.</p>

<h1>try-catch-finally</h1>

<p>The <code>try-catch</code> statement can have an optional <code>finally</code> block. This is run regardless of if an exception is raised. The <code>finally</code> block doesn&#8217;t receive any incoming parameter and can appear no more than once per <code>try</code>:</p>

<pre><code class="groovy">try {
    //statements...
} catch (&lt;Exception type&gt; &lt;var&gt;) {
    //statements...
} finally {
    //statements
}
</code></pre>

<p>In the code below, the <code>println</code> in the finally block will run regardless of whether an exception was raised or the <code>try</code> block completed successfully:</p>

<pre><code class="groovy">try {
    10 / 0
} catch (any) {
    println any.message
} finally {
    println 'I think we survived'
}
</code></pre>

<p>But why use <code>finally</code>? Exceptions are used in a large number of places, including:</p>

<ul>
<li>Failure to read/write a file</li>
<li>Failure to access a database</li>
<li>Trying to access <code>null</code></li>
</ul>

<p>The <code>finally</code> block comes in handy when you need to tidy up resources before either completing the <code>try</code> block or losing control to an exception. You&#8217;ll most commonly see <code>finally</code> used to close files, disconnect from databases or return the system to a state in which it can continue. </p>

<h1>try-finally</h1>

<p>The third form of the <code>try</code> statement doesn&#8217;t provide a <code>catch</code> block:</p>

<pre><code class="groovy">try {
    //statements...
} finally {
    //statements
}
</code></pre>

<p>Essentially we&#8217;re indicating that any exceptions will just be raised up to the caller but we need to tidy up some resources before losing control:</p>

<pre><code class="groovy">try {
    10 / 0
} finally {
    println 'Finally block has been evaluated'
}
</code></pre>

<h1>A Note of Warning</h1>

<p>My examples have largely performed a <code>println</code> and this alone is not acceptable in production code. What a more serious piece of code should do is attempt to recover from the problem, most likely log the issue, and raise the exception to the caller if there&#8217;s no possibility of repair.</p>

<div class="footnotes">
<hr />
<ol>

<li id="fn:1">
<p>I guess I&#8217;ll have to make sure I explain this when we get to Files and Databases. <a href="#fnref:1" title="return to article" class="reversefootnote">&#160;&#8617;</a></p>
</li>

</ol>
</div>


  </div>
  <footer>
    <nav class='part-nav'>
        <a href='../../parts/05_Exceptions/Anatomy.html' rel=prev>&laquo; Previous</a>&nbsp;&bull;&nbsp;<a href='../../parts/05_Exceptions/HowMuch.html' rel=next>Next &raquo;</a>
    </nav>
  </footer>
</article></div>
      </div>
      <div class="col-nav">
        <nav class='article-nav'>
  <header>
  
  <h1>Contents</h1>
  
  </header>
  <ul class='toc-part'>
    <li><a href='../../index.html'>Book home</a>
    <li><a href='index.html'>Exceptions</a>
    <ul>
    
      <li><a href='ThrowableFamily.html'>The Throwable Family</a></li>
    
      <li><a href='CommonExceptions.html'>Common Exceptions</a></li>
    
      <li><a href='Anatomy.html'>Anatomy of an Exception</a></li>
    
      <li><a href='TryCatch.html'>Try-Catch-Finally</a></li>
    
      <li><a href='HowMuch.html'>How Much Should We try?</a></li>
    
      <li><a href='Throw.html'>Causing an Exception</a></li>
    
      <li><a href='CatchingErrors.html'>Catching Errors</a></li>
    
      <li><a href='MethodsExceptions.html'>Methods and Exceptions</a></li>
    
    </ul></li>
  </ul>
</nav>
        <nav class='external-nav'>
          <header>
            <h1>Groovy links</h1>
          </header>
          <ul>
            <li><a href='http://groovy-lang.org/index.html' target='_blank'>Groovy homepage</a></li>
            <li><a href='http://docs.groovy-lang.org/latest/html/gapi/' target='_blank'>GAPI</a></li>
            <li><a href='http://docs.groovy-lang.org/latest/html/api/' target='_blank'>GDK</a></li>
            <li><a href='http://groovy-lang.org/documentation.html' target='_blank'>Groovy Documentation</a></li>
          </ul>
        </nav>
      </div>
    </div>
  </div>
  <footer>
    <p>
      &copy; 2014-2015 <a href='http://www.duncan.dickinson.name' target='_blank'>Duncan Dickinson</a>. See the <a
        href='../../Licence.html'>Licence page</a> for more information
    </p>
    <p>
    Updates regarding this book are posted to <a href="http://news.groovy-tutorial.org">the news site</a>
    </p>
  </footer>
</body>
</html>